### PR TITLE
BUGFIX: Don't create duplicate auto-created child nodes

### LINKED ISSUE #782: Adopting dimension and auto-created child nodes conflict
Jira issue originally created by user @kdambekalns:

Steps to reproduce
1. you have a site with multiple languages
2. you have a document node that has another document as autocreated child node
3. you select that child node and switch the language, answering "yes, copy"

-> you get a duplicate key error.
-> assumption: the parent is copied, the child autocreated, then copied, duplicate.

 Jira-URL: https://jira.neos.io/browse/NEOS-1090

### PR DESCRIPTION
**Pull request by kdambekalns**
This checks for existing auto-created child nodes before they
are created in `createVariantForContext($context)`.

Fixes #782

### CODE REVIEW

File: Neos.ContentRepository/Classes/Domain/Model/Node.php [hunk 1]
```diff
@@ -1731,7 +1731,11 @@ public function createVariantForContext($context)
          * @var $autoCreatedChildNode NodeInterface
          */
         foreach ($autoCreatedChildNodes as $autoCreatedChildNode) {
-            $autoCreatedChildNode->createVariantForContext($context);
+            $existingChildNode = $node->getNode($autoCreatedChildNode->getName());
+            if ($existingChildNode === null || !$existingChildNode->dimensionsAreMatchingTargetDimensionValues()) {
+                // only if needed, see https://github.com/neos/neos-development-collection/issues/782
```
Comment (aertmann) [inline Neos.ContentRepository/Classes/Domain/Model/Node.php]: uhm do we really want such a reference in the code?

Comment (kdambekalns) [reply Neos.ContentRepository/Classes/Domain/Model/Node.php]: Why not? Anyway, feel free to remove it.
