### PR TITLE
BUGFIX: Throw error if Succeeding Sibiling could not be loaded

### LINKED ISSUE #4510: BUG: ProjectionContentGraph - succeedingSiblingRelation can be false
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When migrating the content repository, an error came up. 

Bildschirmfoto 2023-09-14 um 14 27 05

The screenshot says line 266, but it is actually line 265: https://github.com/neos/neos-development-collection/blob/8cb03d53f230cde28b7bcd39736267f3c0e44c3a/Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php#L265. $succeedingSiblingRelation is expected to be an array, but it can also be false(according to the method return type), like in this case. 

### Expected Behavior

I would expect the migration to run through 

### Steps To Reproduce

_No response_

### Environment

```markdown
- Flow:
- Neos: 9.0
- PHP: 8.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pKallert**
closes #4510 

**Review instructions**

If the $succeedingSiblingRelation is false, there is something wrong with the NodeRelationAnchor point and after looking at the code I think we should just abort the whole thing with an error 

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

File: Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php [hunk 1]
```diff
@@ -262,7 +262,15 @@ public function determineHierarchyRelationPosition(
                 ]
             )->fetchAssociative();
 
+            if (!$succeedingSiblingRelation) {
+                throw new \Exception(
```
Comment (bwaidelich) [inline Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]: Do we throw the base exception in similar cases or is there a more specific exception?

File: Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php [hunk 2]
```diff
@@ -262,7 +262,15 @@ public function determineHierarchyRelationPosition(
...
+                    'Could not fetch succeeding sibling relation',
```
Comment (bwaidelich) [inline Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]: The error message could contain some more details (affected nodes, dsp, ...)

File: Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php (hunk 1 above)
Comment (pKallert) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]: Usually we just accept the null and handle it by returning null or zero in methods. I found one occurrence where we throw a runtime exception when we cannot fetch a node: throw new \RuntimeException(sprintf('Failed to fetch node: %s', $e->getMessage()), 1678286030, $e); 

I would suggest using something like a UnexpectedValueException here, since we kind of do expect the succeedingSibling to exist if it is passed to the method.

File: Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php (hunk 2 above)
Comment (pKallert) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]: I adjusted the error message and added the available information

File: Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php (hunk 1 above)
Comment (bwaidelich) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]: Sorry, I didn't realize that this code is invoked from a _projection_.. Throwing exceptions in projections is the last resort as there is no easy way out..
We should find the root cause of the error, i.e.

> there is something wrong with the NodeRelationAnchor point

and check if a bug led to this state.

Maybe you can trace back the code to find out which event triggered the error?

Comment (pKallert) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]: The error occurred only once during one of many migration attempts and I cannot definitely say how I got there. There were lots of errors during lots of attempts, and I can only assume that  it has something to do with this bug: https://github.com/neos/neos-development-collection/issues/4504#issuecomment-1735759814 

Showing an error is an improvement over just having an offset error shown, as it is happening right now. It is worth having a discussion what the expectation would be if the combination of contentstreamID, succeedingSiblingAnchorPoint and dimensionspacepoint does not return a viable relation. Do we use the parentAnchorPoint as a "fallback" or do we assume that at this point something went horribly wrong and show an error?

Comment (bwaidelich) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]: Thanks for the clarification!

> Showing an error is an improvement over just having an offset error shown

Absolutely! My point is, that it is too late at this point. The event has already been published with (potentially) invalid data so we should try to detect and prevent this case _earlier_ already.

> It is worth having a discussion what the expectation would be if the combination of contentstreamID, succeedingSiblingAnchorPoint and dimensionspacepoint does not return a viable relation

Yes!

Comment (mhsdesign) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]: Maybe this bug is solve with all the adjustments from @nezaniel lately?

Comment (nezaniel) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]: As far as I can see this is a bug in the migration script and cannot be solved here

File: Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php [hunk 3]
```diff
@@ -266,6 +266,13 @@ public function determineHierarchyRelationPosition(
                 ]
             )->fetchAssociative();
 
+            if (!$succeedingSiblingRelation) {
+                throw new \Exception(
```
Comment (mhsdesign) [inline Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]:
```suggestion
                throw new \RuntimeException(
```

File: Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php (hunk 1 above)
Comment (mhsdesign) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ProjectionContentGraph.php]: Ill merge this as indeed we throw in many other places also `RuntimeException`'s in the projection even if the case can never happen. Its better than to obscure it. Phpstan should actually enforce this :D

**Review by mhsdesign — APPROVED** [review]
