### PR TITLE
TASK: Make content repository service internal concept and avoid use in Neos.Neos

### LINKED ISSUE #4634: Make `ContentRepositoryServiceFactoryInterface` internal, and remove usages in Neos.Neos
Initially it seemed that the `ContentRepository` should not know much about all things, thus we have the `ContentRepositoryServiceFactoryInterface` pattern.

That lead to `@deprecated really un-nice :D` cr services, that will do funny hanstands to get the variation graph or dimension source:

- DimensionControllerInternals.php
- WorkspacesControllerInternals.php
- DimensionsMenuItemsImplementationInternals.php
- FusionExceptionViewInternals.php

The variation graph and dimension source were exposed on the cr via https://github.com/neos/neos-development-collection/pull/3906

The question is if we should follow that lead and expose all things on the cr via getters (at least the api stuff)
and maybe have an internal `getInternals` method for the leftovers from `ContentRepositoryServiceFactoryDependencies`.

With https://github.com/neos/neos-development-collection/pull/4310 the services where also no singletons per cr anymore see removed `ContentRepositoryRegistry::$contentRepositoryServiceInstances` and by that the `buildService` pattern has no real gain.

@grebaldi suggested that instead of adding a `getInternals` to the cr, we could use a custom content repository factory for testing that will expose the dependencies somehow (hole through space) and thus we would be able to fetch them.

Currently we are relying on reflection to get the NodeFactory for example: https://github.com/neos/neos-development-collection/blob/00a60f391d749b146812b6153362a12d50bff7e3/Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Bootstrap/FeatureContext.php#L130

### PR DESCRIPTION
**Pull request by mhsdesign**
Resolves: #4634

We agreed to keep the ContentRepositoryServiceFactoryInterface but make them internal only used by low level packages like Export and LegacyNodeMigrations.

Neos.Neos and the other mentioned places can already rewrite its DimensionControllerInternals and further to use `ContentRepository::getVariationGraph` or just the content repository directly without indirection.

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

File: Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php [hunk 1]
```diff
@@ -115,6 +115,7 @@ public function subgraphForNode(Node $node): ContentSubgraphInterface
     }
 
     /**
+     * @internal this is a low level extension mechanism and not part of the public API.
```
Comment (mhsdesign) [inline Neos.ContentRepositoryRegistry/Classes/ContentRepositoryRegistry.php]: well to retrieve more or less api things like the `ContentStreamPruner` we probably need to declare `buildService` api, and just say creating your own service is not api?

**Review by bwaidelich — APPROVED** [review]
+1 by reading

**Review by kitsunet — APPROVED** [review]
