### PR TITLE
BUGFIX: node:repair fails with could not be converted to string

### LINKED ISSUE #4794: BUG: node:repair fails with could not be converted to string
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```shell
www-data@a314a99200e9:/app$ ./flow node:repair --dry-run --only removeBrokenEntityReferences
Dry run, not committing any changes.
…
Checking for broken entity references ...
Object of class Neos\Flow\Persistence\Doctrine\Proxies\__CG__\Neos\Media\Domain\Model\ImageVariant could not be converted to string

  Type: Error
  File: Data/Temporary/Development/SubContextWbWeb/Cache/Code/Flow_Object_Classes/Neos_ContentRepository_Command_NodeCommandControllerPlugin.php
  Line: 836
```

### Expected Behavior

The node:repair dry-run does not crash.

### Steps To Reproduce

_No response_

### Environment

```markdown
- Flow: 7.3.11
- Neos: 7.3.12
- PHP: 8.1.21
```

### Anything else?

This is an error in the logging in the _Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php_ line 836

```php
                    if ($convertedProperty instanceof Proxy) {
                        try {
                            $convertedProperty->__load();
                        } /** @noinspection PhpRedundantCatchClauseInspection */ catch (EntityNotFoundException $e) {
                            $nodesWithBrokenEntityReferences[$nodeData->getIdentifier()][$propertyName] = $nodeData;
>>>                         $this->dispatch(self::EVENT_NOTICE, sprintf('Broken reference in "<i>%s</i>" (%s), property "<i>%s</i>" (<i>%s</i>) referring to <i>%s</i>.', $nodeData->getPath(), $nodeData->getIdentifier(), $propertyName, $propertyType, $propertyValue));
                            $brokenReferencesCount ++;
                        }
                    }
```

The `$propertyValue` cannot be logged as _%s_.

### PR DESCRIPTION
**Pull request by christoph-daehne**
Fixes the following crash during node:repair

```shell
./flow node:repair --dry-run --only removeBrokenEntityReferences
Dry run, not committing any changes.

Checking for broken entity references ...
Object of class Neos\Flow\Persistence\Doctrine\Proxies\__CG__\Neos\Media\Domain\Model\ImageVariant could not be converted to string

  Type: Error
  File: Data/Temporary/Development/SubContextWbWeb/Cache/Code/Flow_Object_Classes/Neos_ContentRepository_Command_NodeCommandControllerPlugin.php
  Line: 836
```

resolved #4794

**Upgrade instructions**

- [x] Code follows the PSR-2 coding style
- ~~Tests have been created, run and adjusted as needed~~
    - There are not tests in place and I added none.
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html) -> 7.3
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

File: Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php [hunk 1]
```diff
@@ -833,7 +833,16 @@ public function removeBrokenEntityReferences($workspaceName)
...
                         } /** @noinspection PhpRedundantCatchClauseInspection */ catch (EntityNotFoundException $e) {
                             $nodesWithBrokenEntityReferences[$nodeData->getIdentifier()][$propertyName] = $nodeData;
-                            $this->dispatch(self::EVENT_NOTICE, sprintf('Broken reference in "<i>%s</i>" (%s), property "<i>%s</i>" (<i>%s</i>) referring to <i>%s</i>.', $nodeData->getPath(), $nodeData->getIdentifier(), $propertyName, $propertyType, $propertyValue));
+                            $this->dispatch(self::EVENT_NOTICE, sprintf(
+                                'Broken reference in "<i>%s</i>" (%s), property "<i>%s</i>" (<i>%s</i>)%s.',
+                                $nodeData->getPath(),
+                                $nodeData->getIdentifier(),
+                                $propertyName,
+                                $propertyType,
+                                method_exists($propertyValue, '__toString') ?
```
Comment (kitsunet) [inline Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php:842]: I find the whole "referring to" questionable, because we just don't know what is in there, it could literally be any object, so if __toString is even a sensible representation of the object in question is doubtful, I would actually just remove this. But fine with the fix for now.

**Review by kitsunet — APPROVED** [review]

File: Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php (hunk 1 above)
Comment (christoph-daehne) [reply Neos.ContentRepository/Classes/Command/NodeCommandControllerPlugin.php:842]: I had similar thoughts, but preferred a small chance of helpful information over none ;)

**Review by ahaeslich — APPROVED** [review]
