### PR TITLE
BUGFIX 5222 - use valid workspace name substitutes

### LINKED ISSUE #5222: BUG: missing workspacenames in event metadata get filled in the wrong format
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when running migratevents::migrateMetaDataToWorkspaceName, missing workspace names get filled with the value `'missing:' . $eventMetaData['commandPayload']['contentStreamId']`
This is no longer a valid workspace name and will break stuff afterwards.

### Expected Behavior

The replacement workspace names must be valid

### Steps To Reproduce

_No response_

### Environment

```markdown
- Flow: 9.0.x-dev
- Neos: 9.0.x-dev
- PHP: 8.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nezaniel**
Resolves #5222

**Upgrade instructions**

none

**Review instructions**

none

**Checklist**

- [x] Code follows the PSR-12 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the 9.0 branch
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

File: Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php [hunk 1]
```diff
@@ -298,7 +298,9 @@ public function migrateMetaDataToWorkspaceName(\Closure $outputFn): void
 
             // ... and update the event
             // the payload is only used for rebasing where we override the workspace either way:
-            $eventMetaData['commandPayload']['workspaceName'] = 'missing:' . ($eventMetaData['commandPayload']['contentStreamId'] ?? '');
+            $eventMetaData['commandPayload']['workspaceName'] = WorkspaceName::fromString(
+                'missing-' . \mb_substr($eventMetaData['commandPayload']['contentStreamId'] ?? '', 0, 28)
+            )->value;
```
Comment (bwaidelich) [inline Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php]: Good catch, but with that we'll expose internals. i.e. if the max WorkspaceName length were about to change (even if unlikely) this could break again.
I would suggest to either use [WorkspaceName::MAX_LENGTH](https://github.com/neos/neos-development-collection/blob/2cdeb6a72d2b08ef75f1d8096bc5f679734e8a57/Neos.ContentRepository.Core/Classes/SharedModel/Workspace/WorkspaceName.php#L26) or (probably better) a combination with the dedicated transliteration constructor:
```suggestion
            $eventMetaData['commandPayload']['workspaceName'] = WorkspaceName::transliterateFromString(
                'missing-' . \mb_substr($eventMetaData['commandPayload']['contentStreamId'] ?? '', 0, WorkspaceName::MAX_LENGTH - 8)
            )->value;
```

Comment (nezaniel) [reply Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php]: Agreed, using the constant makes more sense than some arbitrary integer, adjusted

**Review by bwaidelich — APPROVED** [review]
By reading, thanks!

**Review by kitsunet — COMMENTED** [review]
Is taking just the first characters here _safe_? T
he CSId is a UUID and we cut off 12 characters (8 for "missing-" and another 4 because the CsID is already 4 longer than a WorkspaceName can be, so we go 40-4-8, meaning the whole last octet is lost, making collisions much more likely or even sure depending on the used alogrithm... Currently we generate random UUIDs (type 4) but for DB performance I already looked at other types which would be better. TL;DR; this here could make switching hte algo much harder in the future....
I don't have a _great_ alterantive yet, sha1 of the full uuid and then cutting of bits maybe, but overall, we might run into duplication issues quickly-ish here.

I don't want to block but I also don't really want to merge this. it seems like a nasty pit for future us to fall in.

**Comment by nezaniel** [comment]
The "missing-" workspaces are not evaluated anywhere afaik, as they don't exist anyway. Those are an arbitrary placeholder that could as well be "noodle-soup", we just chose something more meaningful

File: Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php (hunk 1 above)
Comment (bwaidelich) [reply Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php]: you kept `fromString` instead of `transliterateFromString` – intentionally?

File: Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php [hunk 2]
```diff
@@ -298,7 +298,9 @@ public function migrateMetaDataToWorkspaceName(\Closure $outputFn): void
 
             // ... and update the event
             // the payload is only used for rebasing where we override the workspace either way:
-            $eventMetaData['commandPayload']['workspaceName'] = 'missing:' . ($eventMetaData['commandPayload']['contentStreamId'] ?? '');
+            $eventMetaData['commandPayload']['workspaceName'] = WorkspaceName::fromString(
+                'missing-' . \mb_substr($eventMetaData['commandPayload']['contentStreamId'] ?? '', 0, WorkspaceName::MAX_LENGTH - 8)
+            )->value;
```
Comment (dlubitz) [inline Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php]: By using transliterateFromString everything should be captured. So this should be enough:

```suggestion
            $eventMetaData['commandPayload']['workspaceName'] = WorkspaceName::transliterateFromString(
                'missing-' . ($eventMetaData['commandPayload']['contentStreamId'] ?? '')
            )->value;
```

Comment (bwaidelich) [reply Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php]: That's almost what I suggested above. But in your example it would always lead to the md5-version if I get it right

Comment (dlubitz) [reply Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php]: The md5 is just a fallback, if the cutting and lowercasing doesn't help.

Comment (dlubitz) [reply Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php]: https://github.com/neos/neos-development-collection/blob/9.0/Neos.ContentRepository.Core/Classes/SharedModel/Workspace/WorkspaceName.php#L90-L93

Comment (bwaidelich) [reply Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php]: Ah right. No need for truncating from the outside 🤘🏻

Comment (nezaniel) [reply Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php]: fine by me

**Review by dlubitz — APPROVED** [review]
