### PR TITLE
BUGFIX 4508 mark dependands of live outdated after direct change

### LINKED ISSUE #4508: BUG: Running `./flow structureadjustments:fix` doesn't mark workspaces as outdated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Running `./flow structureadjustments:fix` will add your changes to the live workspace but not marking any of the other workspaces as outdated. Thus running `./flow workspace:rebaseoutdated` afterwards will do nothing. Logging in again in a user workspace will rebase again.

### Expected Behavior

Workspaces that doesn't contain the adjustments to be marked as outdated.

### Steps To Reproduce

_No response_

### Environment

```markdown
- Flow: 9.0
- Neos: 9.0
- PHP: 8.2
```

Relates: #4442

### PR DESCRIPTION
**Pull request by mhsdesign**
FIXES: https://github.com/neos/neos-development-collection/issues/4508

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

File: Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php [hunk 1]
```diff
@@ -754,8 +753,6 @@ private function whenWorkspaceWasCreated(WorkspaceWasCreated $event): void
     private function whenWorkspaceWasDiscarded(WorkspaceWasDiscarded $event): void
     {
         $this->updateWorkspaceContentStreamId($event->workspaceName, $event->newContentStreamId);
-        $this->markWorkspaceAsOutdated($event->workspaceName);
```
Comment (mhsdesign) [inline Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php:750]: this `markWorkspaceAsOutdated` in discard seems to have been wrong. At least i makes no sense because we get a fresh cs.

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php [hunk 2]
```diff
@@ -56,11 +55,13 @@ public function findWorkspaceByName(WorkspaceName $workspaceName): ?Workspace
     {
         $workspaceByNameStatement = <<<SQL
             SELECT
```
Comment (mhsdesign) [inline Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php]: should we deduplicate this logic using a querybuilder?

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php [hunk 3]
```diff
@@ -56,11 +55,13 @@ public function findWorkspaceByName(WorkspaceName $workspaceName): ?Workspace
...
-                name, baseWorkspaceName, currentContentStreamId, status
+                ws.name, ws.baseWorkspaceName, ws.currentContentStreamId, cs.sourceVersion as lastSourceVersion, scs.version as sourceVersion
             FROM
-                {$this->tableNames->workspace()}
+                {$this->tableNames->workspace()} ws
+                JOIN {$this->tableNames->contentStream()} cs ON cs.id = ws.currentcontentstreamid
+                LEFT JOIN {$this->tableNames->contentStream()} scs ON cs.sourceContentStreamId = scs.id
```
Comment (mhsdesign) [inline Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php]: so the performance trait is this: we still have the status in the workspace, but we have to calculate it slightly more expensive with these two joins.
I cannot say if this is better performance than having on the write side a similar complex update logic for each event. But as `findWorkspaceByName` (and implicitly  `getContentGraph`) trigger this query and are also part of the write side for constraint checks we have to carefully evaluate.

File: Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/WorkspaceState.feature [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+      | baseWorkspaceName  | "live"                 |
+      | newContentStreamId | "shared-cs-identifier" |
+
+    And the command CreateWorkspace is executed with payload:
+      | Key                | Value              |
+      | workspaceName      | "user-ws-two"      |
+      | baseWorkspaceName  | "shared"           |
+      | newContentStreamId | "user-cs-two"      |
+
+  Scenario: Changes to the root workspace render dependents outdated
```
Comment (mhsdesign) [inline Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/WorkspaceState.feature:56]: this tests fails on 9.0-dev

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php (hunk 2 above)
Comment (bwaidelich) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php]: I don't think so

File: Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/WorkspaceState.feature (hunk 4 above)
Comment (bwaidelich) [reply Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/WorkspaceState.feature:56]: why?

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php [hunk 5]
```diff
@@ -136,11 +142,23 @@ public function findContentStreams(): ContentStreams
...
+
+        $status = WorkspaceStatus::UP_TO_DATE;
+        if ($baseWorkspaceName !== null) {
+            // root workspaces can never be out of date and dont have a source content stream
+            $sourceVersion = MaybeVersion::fromVersionOrNull(Version::fromInteger($row['sourceVersion']));
+            $expectedSourceVersion = ExpectedVersion::fromVersion(Version::fromInteger($row['expectedSourceVersion']));
+
+            if (!$expectedSourceVersion->isSatisfiedBy($sourceVersion)) {
+                $status = WorkspaceStatus::OUTDATED;
+            }
```
Comment (bwaidelich) [inline Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php]: Mostly a naming thing, but the "expected version" is something for the write side, i.e. I trigger a command and I expect the model to be of a given version.
In this case it is just two versions of content streams.

**Review by bwaidelich — COMMENTED** [review]
Looks great already, just a comment regarding "expected version"

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php [hunk 6]
```diff
@@ -136,11 +142,23 @@ public function findContentStreams(): ContentStreams
...
     {
+        $baseWorkspaceName = $row['baseWorkspaceName'] !== null ? WorkspaceName::fromString($row['baseWorkspaceName']) : null;
+
+        $status = WorkspaceStatus::UP_TO_DATE;
+        if ($baseWorkspaceName !== null) {
+            // root workspaces can never be out of date and dont have a source content stream
+            $sourceVersion = MaybeVersion::fromVersionOrNull(Version::fromInteger($row['sourceVersion']));
+            $expectedSourceVersion = ExpectedVersion::fromVersion(Version::fromInteger($row['expectedSourceVersion']));
+
+            if (!$expectedSourceVersion->isSatisfiedBy($sourceVersion)) {
```
Comment (mhsdesign) [inline Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php]: rather use equal comparison directly `===`

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php [hunk 7]
```diff
@@ -55,11 +57,13 @@ public function findWorkspaceByName(WorkspaceName $workspaceName): ?Workspace
     {
         $workspaceByNameStatement = <<<SQL
             SELECT
-                name, baseWorkspaceName, currentContentStreamId, status
+                ws.name, ws.baseWorkspaceName, ws.currentContentStreamId, cs.sourceContentStreamVersion as expectedSourceVersion, scs.version as sourceVersion
```
Comment (bwaidelich) [inline Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php]: As discussed: Maybe we can simplify this to sth like:
```suggestion
                ws.name, ws.baseWorkspaceName, ws.currentContentStreamId, cs.sourceContentStreamVersion = scs.version as isUpToDate
```

File: Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php (hunk 1 above)
Comment (nezaniel) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/DoctrineDbalContentGraphProjection.php:750]: ...and it's gone now anyway ^^

File: Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/WorkspaceState.feature (hunk 4 above)
Comment (nezaniel) [reply Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features/Workspaces/WorkspaceState.feature:56]: no longer, I guess

**Review by nezaniel — APPROVED** [review]
Looks nice

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php (hunk 2 above)
Comment (mhsdesign) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php]: hmm i did so anyway hope its fine ^^

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphReadModelAdapter.php [hunk 8]
```diff
@@ -45,26 +47,44 @@ public function __construct(
     ) {
     }
 
-    public function buildContentGraph(WorkspaceName $workspaceName, ContentStreamId $contentStreamId): ContentGraph
-    {
-        return new ContentGraph($this->dbal, $this->nodeFactory, $this->contentRepositoryId, $this->nodeTypeManager, $this->tableNames, $workspaceName, $contentStreamId);
-    }
-
-    public function findWorkspaceByName(WorkspaceName $workspaceName): ?Workspace
+    public function getContentGraph(WorkspaceName $workspaceName): ContentGraph
```
Comment (kitsunet) [inline Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphReadModelAdapter.php:50]: not your original sin (actually is I think, just from another change), but like this is the exact problem iwt the find/get thing. This does a DB query every time, so it hsould be more like find? 🤔 

Either way I think we should do something about this, as getContentGraph() is used ALL over the place. This shouldn't be a query everytime.

**Review by kitsunet — APPROVED** [review]

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php (hunk 2 above)
Comment (bwaidelich) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php]: Of course it is :)

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php (hunk 3 above)
Comment (bwaidelich) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/ContentRepositoryReadModelAdapter.php]: At some point the content graph projections needs to know about changes between streams/workspaces (e.g. to count/diff pending changes etc). Then we can revisit this topic and make it faster if needed

File: Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphReadModelAdapter.php (hunk 8 above)
Comment (bwaidelich) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphReadModelAdapter.php:50]: good point.. this is insofar a new problem as the previous implementation (of `buildContentGraph()`) did _not_ issue an SQL query..
Not sure what to do about it or if we should ignore the mismatch (for now)

Comment (kitsunet) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphReadModelAdapter.php:50]: My worry is more the amount of queries we do alone for this call within a single request...

Comment (mhsdesign) [reply Neos.ContentGraph.DoctrineDbalAdapter/src/ContentGraphReadModelAdapter.php:50]: added todo to readd cache
